version: "3.9"

services:
  queue-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: queue-service

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development
      PORT: 3000
      SERVICE_NAME: spotq-queue-service
      LOG_LEVEL: info

      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/spotq_queue

      REDIS_URL: redis://redis:6379

    depends_on:
      - postgres
      - redis

    networks:
      - spotq-network

  postgres:
    image: postgres:16-alpine

    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: spotq_queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - spotq-network

  redis:
    image: redis:7-alpine

    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - spotq-network

volumes:
  postgres-data:
  redis-data:

networks:
  spotq-network:
    driver: bridge
